### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by jihadbourassi** [rafariva/ANPR-Tensorflow#3]
Hi i am trying to train your model on Morrocan licenceplates wich contain arabic letters, i generated the dataset of images and when i launch training i get the following error 
`Traceback (most recent call last):
  File "train.py", line 250, in <module>
    initial_weights=initial_weights)
  File "train.py", line 213, in train
    test_xs, test_ys = unzip(list(read_data("test/*.png"))[:50])
  File "train.py", line 64, in unzip
    xs, ys = zip(*b)
   ValueError: not enough values to unpack (expected 2, got 0)`

**Comment by bensedik** [comment]
Hi @jihadbourassi , can you explain how you are generate the datasets of images (Morrocan licence plates) ?
Thanks

**Comment by jihadbourassi** [comment]
Of course @bensedik I modified common.py first by adding :

`DIGITS = "0123456789"

 DIGITS_E = "0 1 2 3 4 5 6 7 8 9"

 DIGITS_E1 = "0123456789 "

 DIGITS_0 = "123456789"

 BARRE = "|"

 LETTERS = "وهدجبأ"

 CHARS = LETTERS + DIGITS + BARRE + DIGITS_E + DIGITS_0 + DIGITS_E1`

then i modified gen.py : 

`def generate_code():
    matricule =  "{}{} {}{} {}{} {}{}{}{}".format(
            random.choice(common.DIGITS_0),
            random.choice(common.DIGITS),
            random.choice(common.DIGITS),
            random.choice(common.DIGITS),
            random.choice(common.DIGITS_E1),
            random.choice(common.BARRE),
            random.choice(common.LETTERS),
            random.choice(common.BARRE),
            random.choice(common.DIGITS_0),
            random.choice(common.DIGITS_E1))

    return matricule`

Note : the reason i've put space in some of the strings is because Moroccan licence plates dont have an exact number of charachters it varries from 8 characters to 10 so it can be randomly selected too as a character
![00049999_95304|ه|25_0](https://user-images.githubusercontent.com/48048027/54368580-5354f600-466c-11e9-9ceb-14554015592e.jpg)
![00049973_3509|و|79_0](https://user-images.githubusercontent.com/48048027/54368581-5354f600-466c-11e9-8fc6-9a08ad32b1f0.jpg)
![00049950_14130|ه|6_1](https://user-images.githubusercontent.com/48048027/54368583-5354f600-466c-11e9-8567-0012ecee8554.jpg)

**Comment by bensedik** [comment]
@jihadbourassi , thank you very much for sharing this information.

**Comment by bensedik** [comment]
Hi, @jihadbourassi , i get this error: yntaxError: Non-ASCII character '\xd9', in this line : LETTERS = "وهدجبأ", i think its about "encoding", can you help me again ?

**Comment by jihadbourassi** [comment]
Update : i fixed the issue. The train.py was looking for .png photos on /test, and my test folder contains .jpg only so i changed the code : 

`test_xs, test_ys = unzip(list(read_data("test/*.jpg"))[:50])`

and it's able to read the data now but i got another issue now so i'm closing this one and opening another  one
